# Generated by Django 3.2.8 on 2021-11-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('amount_of_wins', models.IntegerField(default=0)),
                ('amount_of_loses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_of_match', models.CharField(max_length=50)),
                ('tournament_name', models.CharField(max_length=50)),
                ('category', models.ManyToManyField(to='BetApplication.Category')),
                ('first_team', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='match+', to='BetApplication.team')),
                ('second_team', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='match+', to='BetApplication.team')),
            ],
        ),
    ]
