# Generated by Django 3.2.8 on 2021-11-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetApplication', '0005_bet_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='outcome',
            field=models.CharField(max_length=99),
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
